### ISSUE TITLE
Fichiers restants à traduire (utilisez ~~ de chaque côté d'un nom pour le barrer une fois traduit)

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#172]
- Fichiers restant à traduire à part Backstories.xml : 
~~DefInjected/DamageDef/Damages_Stun.xml
DefInjected/RaidStrategyDef/RaidStrategies.xml
DefInjected/RulePackDef/RulePacks_Combat.xml
DefInjected/RulePackDef/RulePacks_DamageEvent.xml~~
DefInjected/RulePackDef/RulePacks_Maneuvers.xml
DefInjected/RulePackDef/RulePacks_NameMaker_World.xml
DefInjected/RulePackDef/RulePacks_NameMakers_Animals.xml
DefInjected/RulePackDef/RulePacks_NameMakers_Factions.xml
DefInjected/RulePackDef/RulePacks_NameMakers_Scenarios.xml
DefInjected/RulePackDef/RulePacks_NameMakers_WorldFeatures.xml
DefInjected/RulePackDef/RulePacks_Seeds.xml
DefInjected/RulePackDef/RulePacks_Transitions.xml
~~DefInjected/StatCategoryDef/StatCategories.xml~~
DefInjected/TaleDef/Tales_Caravan.xml
~~DefInjected/TaleDef/Tales_DoublePawn.xml~~
DefInjected/TaleDef/Tales_Event.xml
DefInjected/TaleDef/Tales_Health.xml
DefInjected/TaleDef/Tales_Incident.xml
DefInjected/TaleDef/Tales_Job.xml
~~DefInjected/ThingDef/Races_Animal_Arid.xml
DefInjected/ThingDef/Races_Animal_Bears.xml
DefInjected/ThingDef/Races_Animal_BigCats.xml
DefInjected/ThingDef/Races_Animal_Birds.xml
DefInjected/ThingDef/Races_Animal_Farm.xml
DefInjected/ThingDef/Races_Animal_Giant.xml
DefInjected/ThingDef/Races_Animal_Hares.xml
DefInjected/ThingDef/Races_Animal_Insect.xml
DefInjected/ThingDef/Races_Animal_Pet.xml
DefInjected/ThingDef/Races_Animal_Rodentlike.xml
DefInjected/ThingDef/Races_Animal_Temperate.xml
DefInjected/ThingDef/Races_Animal_Tropical.xml
DefInjected/ThingDef/Races_Animal_WildCanines.xml
DefInjected/ThingDef/Races_Humanlike.xml
DefInjected/ThingDef/Races_Mechanoid.xml
DefInjected/ThingDef/Buildings_Furniture.xml
DefInjected/ThingDef/Buildings_Security.xml
DefInjected/ThingDef/Buildings_Ship.xml
DefInjected/ThingDef/Buildings_Special.xml
DefInjected/ThingDef/Items_Exotic.xml
DefInjected/ThingDef/Items_Resource_Manufactured.xml
DefInjected/ThingDef/Items_Resource_Shell.xml~~
~~DefInjected/ThingDef/Plants_Cave.xml
DefInjected/ThingDef/Plants_Wild_Arid.xml
DefInjected/ThingDef/Plants_Wild_General.xml
DefInjected/ThingDef/Plants_Wild_Swamp.xml
DefInjected/ThingDef/Plants_Wild_Tropical.xml
DefInjected/ThingDef/Psychite_Pekoe.xml
DefInjected/ThingDef/Various_Stone.xml
DefInjected/ThingDef/Weapons_Guns.xml
DefInjected/ThingDef/Weapons_Melee.xml
DefInjected/ThingDef/Weapons_RangedNeolithic.xml
DefInjected/ThingDef/Weapons_Special.xml~~
~~DefInjected/ThingDef/_Things_Mote.xml~~
DefInjected/ThoughtDef/Smokeleaf.xml
DefInjected/ToolCapacityDef/ToolCapacity.xml
DefInjected/WorkTypeDef/WorkTypes.xml
~~Keyed/Dialog_StatsReports.xml
Keyed/FloatMenu.xml
Keyed/ITabs.xml
Keyed/Menu_Options.xml
Keyed/Menus_Main.xml
Keyed/ScenParts.xml
Keyed/Skills.xml
Keyed/WITabs.xml~~

**Comment by b606** [comment]
Je prends les ThingDef/Items*

**Comment by NeverPire** [comment]
Juste à temps, j'allais les commencer.

**Comment by b606** [comment]
Je passe à Pekoe et Various Stone

**Comment by NeverPire** [comment]
Je suis en train de m'occuper des armes sur mon fork.

**Comment by b606** [comment]
Il faut ajouter à la liste les fichiers où il y a **'<*.tools.*.label>'**

DefInjected/ThingDef/Races_Animal_Arid.xml
DefInjected/ThingDef/Races_Animal_Bears.xml
DefInjected/ThingDef/Races_Animal_BigCats.xml
DefInjected/ThingDef/Races_Animal_Birds.xml
DefInjected/ThingDef/Races_Animal_Farm.xml
DefInjected/ThingDef/Races_Animal_Giant.xml
DefInjected/ThingDef/Races_Animal_Hares.xml
DefInjected/ThingDef/Races_Animal_Insect.xml
DefInjected/ThingDef/Races_Animal_Pet.xml
DefInjected/ThingDef/Races_Animal_Rodentlike.xml
DefInjected/ThingDef/Races_Animal_Temperate.xml
DefInjected/ThingDef/Races_Animal_Tropical.xml
DefInjected/ThingDef/Races_Animal_WildCanines.xml
DefInjected/ThingDef/Races_Humanlike.xml
DefInjected/ThingDef/Races_Mechanoid.xml

Le [script](https://github.com/Sakuukuli/RimWorld-translatescript) que j'ai utilisé ne détecte pas qu'un simple changement maj/minuscule n'est pas une traduction.

**Comment by b606** [comment]
Je passe d'abord aux Keyed/*

**Comment by NeverPire** [comment]
C'est fait. Au sujet des majuscules, ne devrions-nous pas justement revenir aux minuscules pour éliminer tous les conflits en résultant ?

**Comment by b606** [comment]
Comme stratégie, je préconise que ce qui est en minuscule en anglais le reste aussi en FR

**Comment by NeverPire** [comment]
Dans ce cas, je crois qu'il faudrait utiliser l'outil de bilouweb pour repasser tous les labels en minuscules.

**Comment by b606** [comment]
On va d'abord fusionner les PR restants avant de faire çà. On peut créer une autre issue pour le bug de formatage de mechserum du. #174.

**Comment by NeverPire** [comment]
Si le bug provient bien de là parce que je ne vois ce nom-là (Mech-sérum pédagogique (Medicale)) nulle part.

**Comment by NeverPire** [comment]
À première vue, il n'y a rien à traduire dans DefInjected/ThingDef/_Things_Mote.xml vu qu'il y est noté : ""

**Comment by lilidemon** [comment]
DefInjected/ThingDef/Races_Animal_Arid.xml
DefInjected/ThingDef/Races_Animal_Bears.xml
DefInjected/ThingDef/Races_Animal_BigCats.xml
--> Traduits

**Comment by b606** [comment]
Bonjour,
pour les Races_Animal*, il ne faut pas ajouter plus que ce qui est en anglais. Par exemple : l'anglais dit
```
<Cougar.tools.0.label>left claw</Cougar.tools.0.label>
```
En français, cela devrait donc être
```
<Cougar.tools.0.label>griffe gauche</Cougar.tools.0.label>
```
et non pas "griffe gauche de cougar". Sinon, les phrases générées vont être trop longues, du style "**cougar a frappé X avec sa griffe gauche de cougar**".

**Comment by b606** [comment]
lilidemon,
J'ai mis ton patch en pull request #177 pour pouvoir travailler dessus.
A plus :-)

**Comment by b606** [comment]
Il faut faire attention aux variations entre le texte en anglais et le texte en français : certaines phrases ENG ont été modifiées entre temps. J'ai déjà vérifié : ThingDef/Building*, ThingDef/Items*, StatDef/*

**Comment by lilidemon** [comment]
Ok pour les tools des animaux. Je croyais plus à une utilisation des parties du corps comme ceux des trophées. Du genre "Gordon a trouvé une griffe gauche de cougar".
Mais je rectifie ça.

**Comment by lilidemon** [comment]
Modification de mon travail sur : 
DefInjected/ThingDef/Races_Animal_Arid.xml
DefInjected/ThingDef/Races_Animal_Bears.xml
DefInjected/ThingDef/Races_Animal_BigCats.xml
Traduction de : 
DefInjected/ThingDef/Races_Animal_Birds.xml
DefInjected/ThingDef/Races_Animal_Farm.xml
DefInjected/ThingDef/Races_Animal_Giant.xml
DefInjected/ThingDef/Races_Animal_Hares.xml
DefInjected/ThingDef/Races_Animal_Insect.xml
DefInjected/ThingDef/Races_Animal_Pet.xml

**Comment by NeverPire** [comment]
Je mets le fichier "Mote" parmi les traduits ?

**Comment by b606** [comment]
Ok

**Comment by lilidemon** [comment]
Traduction de : 
DefInjected/ThingDef/Races_Animal_Rodentlike.xml
DefInjected/ThingDef/Races_Animal_Temperate.xml
DefInjected/ThingDef/Races_Animal_Tropical.xml
DefInjected/ThingDef/Races_Animal_WildCanines.xml
DefInjected/ThingDef/Races_Humanlike.xml
DefInjected/ThingDef/Races_Mechanoid.xml

**Comment by b606** [comment]
J'ai identifié une quinzaine de tags dont la version anglaise a été modifiée. J'ai poussé ~~./DefInjected/ScenarioDef/Scenarios_Classic.xml~~ sur le PR courant

./DefInjected/ConceptDef/Concepts_TriggeredModal.xml
**TradeGoodsMustBeNearBeacon.helpText**>To send items or silver to orbital traders, you must build an ORBITAL TRADE BEACON and place a stockpile of items near it.


./DefInjected/HediffDef/Hediffs_Local_Implants.xml
**Joywire.labelNoun**>a joywire


./DefInjected/HediffDef/Hediffs_Local_Implants.xml
**Painstopper.labelNoun**>a painstopper


./DefInjected/IncidentDef/Incident_Map_Misc.xml
**ColdSnap.letterText**>An unusual cold snap has set in.\n\nCold snaps can quickly kill by hypothermia. Be sure to build a heated space to survive, wear appropriate apparel, and try to harvest crops before they freeze and die.


./DefInjected/IncidentDef/Incident_Map_Misc.xml
**HeatWave.letterText**>An unusual heat wave has begun.\n\nHeat waves can kill quickly if people start getting heatstroke. Stay cool by building a cooler or getting deep under a mountain. 


./DefInjected/InstructionDef/Instructions.xml
**BuildBeds.text**>Your colonists will now build the room!\n\nNow they need somewhere to sleep. Place three BEDS inside the room.\n\nFind them in the FURNITURE category.\n\nYou can use the {Key:DesignatorRotateLeft} and {Key:DesignatorRotateRight} keys to rotate the building.


./DefInjected/ThingDef/Items_Resource_Stuff.xml
**Uranium.description**>An extremely hard, dense metal. While it is best known for its use powering nuclear reactors, its physical properties also make it excellent in some roles as a tool, weapon, or armor.


./DefInjected/ThingDef/Penoxycyline.xml
**Penoxycyline.description**>A drug for preventing infections from starting. Blocks malaria, sleeping sickness, and plague. Take every five days. Note: This drug does nothing to cure existing infections - it only prevents new ones.


~~./DefInjected/ScenarioDef/Scenarios_Classic.xml~~
**LostTribe.description**>Your tribe was destroyed by the great blood machines sent by the gods. Five of you managed to escape. Now, it's time to build up a new home.\n\nNote: Since you'll start poor and research slowly, this is a difficult scenario.

~~./DefInjected/ScenarioDef/Scenarios_Classic.xml~~
**LostTribe.scenario.description**>Your tribe was destroyed by the great blood machines sent by the gods. Five of you managed to escape. Now, it's time to build up a new home.\n\nNote: Since you'll start poor and research slowly, this is a difficult scenario.

~~./DefInjected/ScenarioDef/Scenarios_Classic.xml~~
**LostTribe.scenario.summary**>Five lost tribespeople attempt to rebuild. Difficult.


~~./DefInjected/ScenarioDef/Scenarios_Classic.xml~~
**TheRichExplorer.description**>People called you crazy for leaving your glitterworld home, but you always yearned to explore the stars - outside the neurosimulator. Now you're at the end of your long journey in cryptosleep, landing on an unknown rimworld to see what it's like.\n\nNote: Since your starting character will lack some skills, this is an especially difficult scenario in the early game.


~~./DefInjected/ScenarioDef/Scenarios_Classic.xml~~
**TheRichExplorer.scenario.description**>People called you crazy for leaving your glitterworld home, but you always yearned to explore the stars - outside the neurosimulator. Now you're at the end of your long journey in cryptosleep, landing on an unknown rimworld to see what it's like.\n\nNote: Since your starting character will lack some skills, this is an especially difficult scenario in the early game.

~~./DefInjected/ScenarioDef/Scenarios_Classic.xml~~
**TheRichExplorer.scenario.summary**>One rich explorer out to experience the universe. Extra difficult.

./DefInjected/WorkTypeDef/WorkTypes.xml
**Construction.description**>Build things that you've designated, and fix damaged or broken-down buildings.

**Comment by b606** [comment]
./DefInjected/ToolCapacityDef/ToolCapacity.xml rajouté dans la liste

**Comment by b606** [comment]
Encore des tags modifiés !!! (vérifier aussi les tags _Frame correspondants)


./DefInjected/ResearchProjectDef/ResearchProjects_Tier1_Misc.xml
**Smithing.description**>Build smithies for crafting metal weapons and tools.nnAllows you to craft simple weapons like knives, gladii, and maces.


./DefInjected/ResearchProjectDef/ResearchProjects_Tier4_Misc.xml
**VitalsMonitor.description**>Allows colonists to build vitals monitors which improve medical care when placed next to hospital beds.


./DefInjected/StatDef/Stats_Pawns_WorkRecipes.xml
**MechanoidOperationSuccessChance.description**>The chance that a character will perform an operation on a mechanoid successfully. Failures can result loss of harvested parts and damage to the subject.


./DefInjected/TerrainDef/Terrain_Floors.xml
**WoodPlankFloor.description**>Wood plank flooring. For that warm, homey feeling. While it is easy to lay, it is also flammable.


./DefInjected/ThingDef/Buildings_Furniture.xml
**TorchLamp.description**>A wooden torch for lighting an area. People need light to move and work at full speed. Can be automatically refueled with wood. Produces a small amount of heat.


./DefInjected/ThingDef/Buildings_Furniture.xml
**StandingLamp.description**>Standing lamp that lights an area. People need light to move and work at full speed.


./DefInjected/ThingDef/Weapons_RangedNeolithic.xml
**Pila.description**>Pila are spears for throwing. They take a long time to throw, and move slowly, but one hit can do heavy damage. The singular of pila is pilum.


./DefInjected/ThingDef/Weapons_RangedNeolithic.xml
**Bow_Short.description**>A simple short selfbow made from a single piece of wood.


./DefInjected/TraitDef/Traits_Singular.xml
**Pyromaniac.degreeDatas.0.description**>NAME loves fire. HECAP will never extinguish fires. To relieve stress, HE will occasionally go on random fire starting sprees. This happens more often if HIS mood is low.


./Keyed/Credits.xml
**Credit_MusicAndSound**>Audio


./Keyed/Credits.xml
**Credit_GameArt**>Art


./Keyed/Designators.xml
**DesignatorAreaBuildRoofExpandDesc**>Colonists will build roofs in this area.


./Keyed/Designators.xml
**DesignatorAreaIgnoreRoofExpand**>Ignore roof area


./Keyed/Designators.xml
**DesignatorAreaIgnoreRoofExpandDesc**>Colonists will ignore roofs in this area.


./Keyed/ScenParts.xml
**ScenPart_StartWithPawns**>Start with {0} people, chosen from {1}.

**Comment by b606** [comment]
Reste

tags modifiés : 
./DefInjected/StatDef/Stats_Pawns_WorkRecipes.xml
./Keyed/Credits.xml
./Keyed/Designators.xml

traduction : 
Backstories.xml
RulePack*
Tales*
DefInjected/StatCategoryDef/StatCategories.xml
DefInjected/ThoughtDef/Smokeleaf.xml
DefInjected/ToolCapacityDef/ToolCapacity.xml
DefInjected/WorkTypeDef/WorkTypes.xml

**Comment by b606** [comment]
Comparaison avec le texte actuel FR ~ version anglaise précédente :
./Keyed/Credits.xml
  **Credit_MusicAndSound**>Audio (FR : Musiques et bruitages)
  **Credit_GameArt**>Art (FR : Graphismes du jeu)
La version française fait beuhh :-) C'est peut-être çà qui a fait qu'ils ont changé.

**Comment by b606** [comment]
DefInjected/StatCategoryDef/StatCategories.xml
<Surgery.label>Surgical</Surgery.label>
A moins que quelqu'un trouve où s'affiche ce tag dans le jeu, je propose qu'on le laisse tel quel. Ce sera plus facile de détecter qu'il n'a pas été traduit

**Comment by NeverPire** [comment]
Je n'en ai aucune idée, donc je le laisserai en l'état.

**Comment by b606** [comment]
typo dans 
DefInjected/WorkTypeDef/WorkTypes.xml
<Crafting.labelShort>**Artisant**</Crafting.labelShort>
Ces tags ne semblent pas cohérents avec les autres du même type
<Art.label>Art</Art.label>
<Art.labelShort>Art</Art.labelShort>
<Mining.label>Mine</Mining.label>

**Comment by lilidemon** [comment]
J'ai été un peu prise ces derniers jours, je devrais pouvoir traduire 2-3 trucs dimanche.
Je suis une formation en plus de mon boulot, alors autant vous dire que l'emploi du temps est serré. ^^
Je m'attaquerai aux TaleDef.

**Comment by b606** [comment]
J'ai passé DefInjected/StatCategoryDef/StatCategories.xml <Surgery.label> non traduit en issue pour référence

**Comment by lilidemon** [comment]
J'attaque le fichier Tales_job, gros morceau. Je vais étaler mon travail sur plusieurs jours.

**Comment by b606** [comment]
Bonjour,
On ferme cette issue ?

**Comment by kiliak** [comment]
Pour moi oui
